# Grupo de servidores de nodos
[kubernetesnodos]
ubuntunodo2 ansible_host=192.168.1.50 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa
ubuntunodo1 ansible_host=192.168.1.14 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa

# Grupo de maquinas sólo de pruebas
[pruebas]
redhat3 ansible_host=192.168.1.106 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa
debian13 ansible_host=192.168.1.109 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa

# Grupo de servidores con funciones
[funciones]
tarlogic1 ansible_host=192.168.1.103 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa
ubuntuawx ansible_host=192.168.1.107 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa
weblogic2 ansible_host=192.168.1.200 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa

[proxmox]
ubuntunodo2
ubuntunodo1
debian13
tarlogic1
ubuntuawx
redhat3

[vmware]
weblogic2

# ENLACE PARA ASOCIAR LA PALABRA "nodos" A KUBERNETESNODOS
[nodos:children]
kubernetesnodos

# Grupo general
[all:vars]
ansible_python_interpreter=/usr/bin/python3
