---
- name: Instalar Zabbix Agent 2 en Linux (Debian + RedHat) y registrar en Zabbix
  hosts: nodos
  become: yes

  vars:
    zabbix_version: "7.0"
    zabbix_server_ip: "192.168.1.103"
    zabbix_api_url: "http://{{ zabbix_server_ip }}/zabbix"
    zabbix_api_user: "Admin"
    zabbix_api_pass: "Churrita10."
    
    # URLs de los REPOSITORIOS oficiales
    zabbix_deb_repo_url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+ubuntu{{ ansible_distribution_version }}_all.deb"
    zabbix_rpm_repo_url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-latest.el{{ ansible_distribution_major_version }}.noarch.rpm"

  tasks:

    # -------------------------
    # CONFIGURACIÓN REPOSITORIO DEBIAN/UBUNTU
    # -------------------------
    - name: Configurar repositorio en Debian/Ubuntu
      ansible.builtin.apt:
            deb: "{{ zabbix_deb_repo_url }}"
            state: present

    - name: Actualizar caché de apt
      ansible.builtin.apt:
            update_cache: yes
      when: ansible_os_family == "Debian"
      become: yes

    # -------------------------
    # CONFIGURACIÓN REPOSITORIO REDHAT/CENTOS/ROCKY
    # -------------------------
    - name: Configurar repositorio de Zabbix (RedHat/DNF)
      ansible.builtin.dnf:
        name: "{{ zabbix_rpm_repo_url }}"
        state: present
        disable_gpg_check: yes
      when: ansible_os_family == "RedHat"

    # -------------------------
    # INSTALACIÓN DEL AGENTE (Paquete nativo)
    # -------------------------
    - name: Instalar Zabbix Agent 2 (Debian/Ubuntu)
      ansible.builtin.apt:
        name: zabbix-agent2
        state: present
      when: ansible_os_family == "Debian"
      become: yes

    - name: Instalar Zabbix Agent 2 (RedHat OS)
      ansible.builtin.dnf:
        name: zabbix-agent2
        state: present
      when: ansible_os_family == "RedHat"
      become: yes

    # -------------------------
    # CONFIGURACIÓN
    # -------------------------
    - name: Configurar Zabbix Agent 2
      ansible.builtin.template:
        src: zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
        mode: '0644'
      notify: restart zabbix-agent2

    # -------------------------
    # SERVICIO
    # -------------------------
    - name: Habilitar y arrancar Zabbix Agent 2
      ansible.builtin.service:
        name: zabbix-agent2
        state: started
        enabled: yes

    # -------------------------
    # REGISTRO EN ZABBIX (API)
    # -------------------------
    - name: Registrar host en el servidor Zabbix
      community.zabbix.zabbix_host:
        server_url: "{{ zabbix_api_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_pass }}"
        host_name: "{{ inventory_hostname }}"
        visible_name: "{{ inventory_hostname }}"
        status: enabled
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ ansible_default_ipv4.address }}"
            port: 10050
        groups:
          - Linux Servers
        templates:
          - Linux by Zabbix Agent
        state: present
        delegate_to: localhost
  become: no

  handlers:
    - name: restart zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted